#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${__dir}"

if [[ -f day-$1/part2.ts ]]; then
    deno run --allow-read=day-$1/ --watch day-$1/part2.ts
elif [[ -f day-$1/part1.ts ]]; then
    deno run --allow-read=day-$1/ --watch day-$1/part1.ts
else
    echo "No such day"
fi
